version: '3'

services:
  registry:
  # cf.: https://docs.docker.com/registry/deploying/
    image: registry:2.6.2
    ports:
      - "5000:5000"
    volumes:
      - docker_images:/var/lib/registry
      - docker_certs:/certs
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/domain.key

  # cf.: https://github.com/kwk/docker-registry-frontend/tree/v2
  ui:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "8080:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
      # ENV_DOCKER_REGISTRY_USE_SSL: 1
      # ENV_REGISTRY_PROXY_FQDN: ${HOSTNAME}
    links:
      - registry

volumes:
    docker_images:
    docker_certs:
